### ISSUE TITLE
Chooser fields empty on init

### ISSUE THREAD

**Issue by lohmander** [wagtail/wagtail-react-streamfield#50] opened 2019-09-13 07:28 UTC
All the chooser fields (ie. ImageChooser, PageChooser, etc.) are empty when initialized for me. I have the app first in my installed apps, so the solution that solved #47 did not solve the problem for me.

Getting the following JS errors, for what it's worth:

<img width="786" alt="Screen Shot 2019-09-13 at 4 27 16 PM" src="https://user-images.githubusercontent.com/2197050/64844692-66f50f80-d643-11e9-97e0-e14f83ac7a27.png">

**Comment by BertrandBordage** [comment] 2019-10-08 15:57
Could you tell us which versions of Django, Wagtail & wagtail-react-streamfield are you using?

**Comment by BertrandBordage** [comment] 2020-08-05 11:59
Closing for now, as I am not able to reproduce the issue.

**Closed by BertrandBordage** 2020-08-05 11:59 UTC
Labels: needs info
