### ISSUE TITLE
Limitations with block naming

### ISSUE THREAD

**Issue by fpoulain** [wagtail/wagtail-react-streamfield#54] opened 2020-02-26 09:43 UTC
Hi,

Thank you for all your work. I use react-streamfield since about 18 month and I built some websites using exotic names containing '+' (plus) or '.' (dots).

It seems that theses names now break react streamfield.

Btw there is no advertising about it. Block._check_name don't refers to plus or dots.

Prior moving to wagtail-2.7, it worked (last known working version from pip : 1.3.5).

(Actually I am not sure if I should report this as a Wagtail bug.)

**Comment by fpoulain** [comment] 2020-04-09 09:12
Ping ? (I am still not sure if I should report this as a Wagtail bug.)

**Comment by BertrandBordage** [comment] 2020-08-05 10:51
Thanks for the report, I am going to investigate this, I don’t immediately know why it’s failing.

**Comment by BertrandBordage** [comment] 2020-08-05 12:05
Could you elaborate more? I tested with Wagtail 2.9.3 & wagtail-react-streamfield 1.3.6, and didn’t face the issue with a rather tricky name, as you can see below. It correctly rendered and saved:
![image](https://user-images.githubusercontent.com/1119169/89410820-b4c7aa00-d724-11ea-9fb9-bc5b36975b16.png)
![image](https://user-images.githubusercontent.com/1119169/89410787-a5e0f780-d724-11ea-9c22-eda759d0d7da.png)

**Comment by fpoulain** [comment] 2020-08-05 13:24
Hi,

Very thanks for your attention.

Unfortunately I am able to reproduce it in wagtail 2.7 and wagtail 2.9.

I started a repo here : https://forge.cliss21.org/fpoulain/issue54

After cloning it you can:
* make init
* an editor will open; uncomment "ENV=development", save and quit
* ./manage.py createsuperuser
* make serve
* visit http://127.0.0.1:8000/admin/pages/3/edit/

**Comment by BertrandBordage** [comment] 2020-08-05 14:03
I could see the issue when using your project but… Your project is not using wagtail-react-streamfield!
The issue is really with Wagtail itself. It may seem that Wagtail now uses wagtail-react-streamfield, but it actually only uses the CSS of react-streamfield, adjusted to work with the old StreamField. Wagtail-react-streamfield is unfortunately still not yet in Wagtail due to long discussions and concerns regarding compatibility with a few third party blocks. For the record, we are arriving at a resolution for all these points, which will be documentation on how to migrate tricky third party block.

So I’m closing this issue for now, marking it as invalid, sorry :) Please open a Wagtail issue instead and reference this one. Thanks!

**Closed by BertrandBordage** 2020-08-05 14:03 UTC
Labels: needs info

**Comment by gasman** [comment] 2020-08-05 14:10
These names are invalid in vanilla Wagtail too, [as per the docs](https://docs.wagtail.io/en/stable/topics/streamfield.html):

> ‘name’ is used to identify the block type within templates and the internal JSON representation (and should follow standard Python conventions for variable names: lower-case and underscores, no spaces)

**Comment by BertrandBordage** [comment] 2020-08-05 14:15
But it works with wagtail-react-streamfield because it only uses UUIDs to identify field instances :stuck_out_tongue:

**Comment by fpoulain** [comment] 2020-08-05 14:18
@BertrandBordage ok sorry, I have been confused. I started to migrate a project from wagtail 2.4 + wagtail-react-streamfield to wagtail 2.7. I thought the latter has included wagtail-react-streamfield.

@gasman Ok, so i was misled by Block._check_name which was too lazy. Is it useful to propose a patch making it more restrictive?

**Comment by fpoulain** [comment] 2020-08-05 14:30
> But it works with wagtail-react-streamfield because it only uses UUIDs to identify field instances stuck_out_tongue

And installing wagtail-react-streamfield hide my problem. Thanks for the hint.

**Comment by gasman** [comment] 2020-08-05 14:37
> @gasman Ok, so i was misled by Block._check_name which was too lazy. Is it useful to propose a patch making it more restrictive?

Sure, sounds good. I think it makes sense for `Block._check_name` to reject anything which is not valid as a python variable name (so, for example, it should reject any names with invalid symbols, but it should still allow uppercase).

**Comment by fpoulain** [comment] 2020-08-05 14:41
ok; I will propose a PR.
